{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmzqc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmzqc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmzqc/rmzqc_{{ version }}.tar.gz
  sha256: facf979d96583fd67fab45ccc7a3c88ed5db0f9dcecf3557482d3286071b9d2d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-r6p
    - r-jsonlite
    - r-jsonvalidate
    - r-knitr
    - r-ontologyindex
    - r-rmarkdown
    - r-testthat
  run:
    - r-base
    - r-r6
    - r-r6p
    - r-jsonlite
    - r-jsonvalidate
    - r-knitr
    - r-ontologyindex
    - r-rmarkdown
    - r-testthat

test:
  commands:
    - $R -e "library('rmzqc')"           # [not win]
    - "\"%R%\" -e \"library('rmzqc')\""  # [win]

about:
  home: https://github.com/MS-Quality-hub/rmzqc
  license: MIT
  summary: Reads, writes and validates 'mzQC' files. The 'mzQC' format is a standardized file format for the exchange, transmission, and archiving of quality metrics derived from biological mass spectrometry data, as defined by the HUPO-PSI (Human Proteome Organisation - Proteomics Standards Initiative) Quality Control working
    group. See <https://hupo-psi.github.io/mzQC/> for details.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
